// <auto-generated />
using System;
using System.Collections.Generic;
using MarketDataIngestionService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketDataIngestionService.Migrations
{
    [DbContext(typeof(MarketDataDbContext))]
    partial class MarketDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClassLibrary.Domain.Entities.Cestas.CestasRecomendacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("cestas_recomendacao", (string)null);
                });

            modelBuilder.Entity("ClassLibrary.Domain.Entities.Cestas.ItensCesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CestaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Percentual")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CestaId");

                    b.ToTable("itens_cesta", (string)null);
                });

            modelBuilder.Entity("ClassLibrary.Domain.Entities.Clientes.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ValorMensal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasDatabaseName("ux_clientes_cpf");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("ClassLibrary.Domain.Entities.Clientes.ContasGraficas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NumeroConta")
                        .IsUnique()
                        .HasDatabaseName("ux_numeroConta_contas");

                    b.ToTable("contas_graficas", (string)null);
                });

            modelBuilder.Entity("ClassLibrary.Domain.Entities.CompraDistribuicao.Custodias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContasGraficasId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoMedio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ContasGraficasId");

                    b.ToTable("custodias", (string)null);
                });

            modelBuilder.Entity("ClassLibrary.Domain.Entities.CompraDistribuicao.Distribuicoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("distribuicoes", (string)null);
                });

            modelBuilder.Entity("ClassLibrary.Domain.Entities.CompraDistribuicao.OrdensCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaMasterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("TipoMercado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContaMasterId");

                    b.ToTable("ordens_compra", (string)null);
                });

            modelBuilder.Entity("ClassLibrary.Domain.Entities.Cotacoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPregao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoAbertura")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoFechamento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoMaximo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id");

                    b.ToTable("cotacoes", (string)null);
                });

            modelBuilder.Entity("ClassLibrary.Domain.Entities.RebalanceamentoIR.EventosIR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("PublicadoKafka")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorIR")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("eventos_ir", (string)null);
                });

            modelBuilder.Entity("ClassLibrary.Domain.Entities.RebalanceamentoIR.Rebalanceamentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRebalanceamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TickerComprado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TickerVendido")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("ValorVenda")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("rebalanceamentos", (string)null);
                });

            modelBuilder.Entity("Itau.InvestCycleEngine.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("Itau.InvestCycleEngine.Domain.Entities.InvestmentAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BrokerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("investment_accounts", (string)null);
                });

            modelBuilder.Entity("Itau.InvestCycleEngine.Domain.Entities.PlanExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("RunAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("plan_executions", (string)null);
                });

            modelBuilder.Entity("Itau.InvestCycleEngine.Domain.Entities.ProgrammedPurchasePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NextRunAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.ComplexProperty<Dictionary<string, object>>("AmountPerRun", "Itau.InvestCycleEngine.Domain.Entities.ProgrammedPurchasePlan.AmountPerRun#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("amount_per_run");

                            b1.Property<int>("Currency")
                                .HasColumnType("int")
                                .HasColumnName("amount_currency");
                        });

                    b.HasKey("Id");

                    b.ToTable("programmed_purchase_plans", (string)null);
                });

            modelBuilder.Entity("ClassLibrary.Domain.Entities.Cestas.ItensCesta", b =>
                {
                    b.HasOne("ClassLibrary.Domain.Entities.Cestas.CestasRecomendacao", "Cesta")
                        .WithMany()
                        .HasForeignKey("CestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cesta");
                });

            modelBuilder.Entity("ClassLibrary.Domain.Entities.Clientes.ContasGraficas", b =>
                {
                    b.HasOne("ClassLibrary.Domain.Entities.Clientes.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ClassLibrary.Domain.Entities.CompraDistribuicao.Custodias", b =>
                {
                    b.HasOne("ClassLibrary.Domain.Entities.Clientes.ContasGraficas", "ContasGraficas")
                        .WithMany()
                        .HasForeignKey("ContasGraficasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContasGraficas");
                });

            modelBuilder.Entity("ClassLibrary.Domain.Entities.CompraDistribuicao.OrdensCompra", b =>
                {
                    b.HasOne("ClassLibrary.Domain.Entities.Clientes.ContasGraficas", "ContaGrafica")
                        .WithMany()
                        .HasForeignKey("ContaMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("ClassLibrary.Domain.Entities.RebalanceamentoIR.EventosIR", b =>
                {
                    b.HasOne("ClassLibrary.Domain.Entities.Clientes.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ClassLibrary.Domain.Entities.RebalanceamentoIR.Rebalanceamentos", b =>
                {
                    b.HasOne("ClassLibrary.Domain.Entities.Clientes.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Itau.InvestCycleEngine.Domain.Entities.ProgrammedPurchasePlan", b =>
                {
                    b.OwnsOne("Itau.InvestCycleEngine.Domain.Entities.PlanSchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("ProgrammedPurchasePlanId")
                                .HasColumnType("char(36)");

                            b1.Property<int?>("DayOfMonth")
                                .HasColumnType("int")
                                .HasColumnName("schedule_day_of_month");

                            b1.Property<int?>("DayOfWeek")
                                .HasColumnType("int")
                                .HasColumnName("schedule_day_of_week");

                            b1.Property<int>("Frequency")
                                .HasColumnType("int")
                                .HasColumnName("schedule_frequency");

                            b1.Property<int>("Interval")
                                .HasColumnType("int")
                                .HasColumnName("schedule_interval");

                            b1.Property<TimeSpan>("RunAtLocalTime")
                                .HasColumnType("time(6)")
                                .HasColumnName("schedule_run_at_local_time");

                            b1.HasKey("ProgrammedPurchasePlanId");

                            b1.ToTable("programmed_purchase_plans");

                            b1.WithOwner()
                                .HasForeignKey("ProgrammedPurchasePlanId");
                        });

                    b.Navigation("Schedule")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
