services:
  mysql:
    image: mysql:8.4
    container_name: investcycle-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: investCycle
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p12345678 --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka:
    image: apache/kafka:3.9.1
    container_name: investcycle-kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: investcycle-kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: investcycle-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      - kafka

  market-data-ingestion-service:
    container_name: investcycle-market-data
    build:
      context: .
      dockerfile: MarketDataIngestionService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      Cors__AllowedOrigins: http://localhost:8081,http://127.0.0.1:8081,http://localhost:8080,http://127.0.0.1:8080
      ConnectionStrings__mysql: Server=mysql;Port=3306;Database=investCycle;Uid=root;Pwd=12345678;
    ports:
      - "5136:8080"
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started

  scheduled-purchase-engine-service:
    container_name: investcycle-scheduled-purchase
    build:
      context: .
      dockerfile: ScheduledPurchaseEngineService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      Cors__AllowedOrigins: http://localhost:8081,http://127.0.0.1:8081,http://localhost:8080,http://127.0.0.1:8080
      ConnectionStrings__mysql: Server=mysql;Port=3306;Database=investCycle;Uid=root;Pwd=12345678;
    ports:
      - "5115:8080"
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started

volumes:
  kafka_data:
  mysql_data:
